/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import controller.conexionController;
import dao.VendedorDAO;
import java.sql.Connection;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import metodos.ListaEnlazadaVendedores;
import modelos.VendedorEntity;

/**
 *
 * @author jwsb1
 */
public class InternalVendedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalVendedor
     */
    public InternalVendedor() {
        initComponents();
        obtenerVendedoresTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void obtenerVendedoresTable() {
        Connection con = conexionController.conectar();
        VendedorDAO vendedorDAO = new VendedorDAO(con);
        List<VendedorEntity> listaVendedores = vendedorDAO.obtenerVendedores();
        
        ListaEnlazadaVendedores listaEnlazada = new ListaEnlazadaVendedores();
        for (VendedorEntity v : listaVendedores) {
            listaEnlazada.agregar(v);
        }
        
        listaEnlazada.mostrar();
        
        String[] columnNames = {"NombreCompleto", "DNI", "Acumulados", "Bonificacion"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnNames, 0);
        
        for (VendedorEntity v : listaVendedores) {
            Object[] fila = {v.getNombres()+" "+v.getApellidos(), v.getDni(), v.getPuntosxacum(), v.getPuntosxbon()};
            modelo.addRow(fila);
        }
        
        tablaVendedores.setModel(modelo);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        BotonEliminar = new javax.swing.JButton();
        BotonRegistrar = new javax.swing.JButton();
        BotonEditar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Apellido = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        txt_Puntos = new javax.swing.JTextField();
        txt_Bonificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Correo = new javax.swing.JTextField();
        ButtonLE_AgregarInicio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ButtonLE_AgregarFinal = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 204));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion de Vendedores");

        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Completo", "DNI", "Puntos Acumulado", "Bonificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        BotonEliminar.setBackground(new java.awt.Color(255, 0, 102));
        BotonEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonRegistrar.setBackground(new java.awt.Color(0, 102, 255));
        BotonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        BotonEditar1.setBackground(new java.awt.Color(51, 255, 0));
        BotonEditar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonEditar1.setForeground(new java.awt.Color(255, 255, 255));
        BotonEditar1.setText("Editar");
        BotonEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditar1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txt_Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txt_Apellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Apellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txt_DNI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_DNI.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txt_Puntos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Puntos.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        txt_Bonificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Bonificacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombres:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Apellidos:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("DNI:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Puntos:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Bonificacion:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Correo:");

        txt_Correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Correo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Bonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Bonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Puntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        ButtonLE_AgregarInicio.setBackground(new java.awt.Color(204, 51, 255));
        ButtonLE_AgregarInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLE_AgregarInicio.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLE_AgregarInicio.setText("Agregar Final");
        ButtonLE_AgregarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLE_AgregarInicioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Lista Enlazada");

        ButtonLE_AgregarFinal.setBackground(new java.awt.Color(255, 255, 51));
        ButtonLE_AgregarFinal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLE_AgregarFinal.setText("Agregar Inicio");
        ButtonLE_AgregarFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLE_AgregarFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ButtonLE_AgregarInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonLE_AgregarFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                            .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(403, 403, 403))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonLE_AgregarInicio)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonLE_AgregarFinal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
        
        JFrame frameActual = (JFrame) SwingUtilities.getWindowAncestor(this);
        frameActual.dispose();
        
        RegistroVendedor registroVendedor = new RegistroVendedor();
        int ancho = registroVendedor.getWidth();
        int alto = registroVendedor.getHeight();
        DashboardAdmin nuevoFrame =new DashboardAdmin(ancho, alto);
        nuevoFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        nuevoFrame.JDeskPanel = new JDesktopPane();
        nuevoFrame.add(nuevoFrame.JDeskPanel.add(registroVendedor));
        registroVendedor.setVisible(true);
        
        try {
            registroVendedor.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BotonEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEditar1ActionPerformed

    private void ButtonLE_AgregarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLE_AgregarInicioActionPerformed
        Connection con = conexionController.conectar();
        VendedorDAO vendedorDAO = new VendedorDAO(con);
        List<VendedorEntity> listaVendedores = vendedorDAO.obtenerVendedores();
        
        ListaEnlazadaVendedores listaEnlazada = new ListaEnlazadaVendedores();
        for (VendedorEntity v : listaVendedores) {
            listaEnlazada.agregar(v);
        }
        
        String nombres = txt_Nombre.getText();
        String apellidos = txt_Apellido.getText();
        String dni = txt_DNI.getText();
        String correo = txt_Correo.getText();
        int bonificacion = Integer.parseInt(txt_Bonificacion.getText());
        int puntos = Integer.parseInt(txt_Puntos.getText());
        
        VendedorEntity vendedor = new VendedorEntity(nombres, apellidos, correo, dni, puntos, bonificacion);
        
        listaEnlazada.agregar(vendedor);
        
        String[] columnNames = {"NombreCompleto", "DNI", "Acumulados", "Bonificacion"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnNames, 0);
        
        for (VendedorEntity v : listaEnlazada.obtenerVendedoresComoLista()) {
            System.out.println(v);
            Object[] fila = {v.getNombres()+" "+v.getApellidos(), v.getDni(), v.getPuntosxacum(), v.getPuntosxbon()};
            modelo.addRow(fila);
        }
        
        tablaVendedores.setModel(modelo);
    }//GEN-LAST:event_ButtonLE_AgregarInicioActionPerformed

    private void ButtonLE_AgregarFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLE_AgregarFinalActionPerformed
        Connection con = conexionController.conectar();
        VendedorDAO vendedorDAO = new VendedorDAO(con);
        List<VendedorEntity> listaVendedores = vendedorDAO.obtenerVendedores();
        
        ListaEnlazadaVendedores listaEnlazada = new ListaEnlazadaVendedores();
        for (VendedorEntity v : listaVendedores) {
            listaEnlazada.agregarInicio(v);
        }
        
        String nombres = txt_Nombre.getText();
        String apellidos = txt_Apellido.getText();
        String dni = txt_DNI.getText();
        String correo = txt_Correo.getText();
        int bonificacion = Integer.parseInt(txt_Bonificacion.getText());
        int puntos = Integer.parseInt(txt_Puntos.getText());
        
        VendedorEntity vendedor = new VendedorEntity(nombres, apellidos, correo, dni, puntos, bonificacion);
        
        listaEnlazada.agregar(vendedor);
        
        String[] columnNames = {"NombreCompleto", "DNI", "Acumulados", "Bonificacion"};
        
        DefaultTableModel modelo = new DefaultTableModel(columnNames, 0);
        
        for (VendedorEntity v : listaEnlazada.obtenerVendedoresComoLista()) {
            System.out.println(v);
            Object[] fila = {v.getNombres()+" "+v.getApellidos(), v.getDni(), v.getPuntosxacum(), v.getPuntosxbon()};
            modelo.addRow(fila);
        }
        
        tablaVendedores.setModel(modelo);
    }//GEN-LAST:event_ButtonLE_AgregarFinalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEditar1;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton ButtonLE_AgregarFinal;
    private javax.swing.JButton ButtonLE_AgregarInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txt_Apellido;
    private javax.swing.JTextField txt_Bonificacion;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Puntos;
    // End of variables declaration//GEN-END:variables
}
